package.json
Updating bootstrap to the next pre-release breaks build as it removes some files. Fixing this problem led to new problems with the appearance of certain elements in some browsers. These would probably have to be fixed again when the next pre-release comes out, so I suggest following the path of least resistance: pin the working bootstrap pre-release version in the requirements and integrate the new bootstrap 4  it comes out.
=> fix broken build by pinning bs version

src/components/FormFields/index.js, src/i18n/fi.json, src/utils/formDataMapping.js
Target group keyword set is changed from `helfi:audiences` to `helsinki:audiences`. When posting an event to the backend, old hel.fi keywords that correspond to selected new keywords are posted also for now.
=> Helsinki audience

config/webpack/prod.js
Fix #159 
Make "production quality" source maps in, well, production.
=> Source maps enabled in production build

src/components/EventGrid/index.js, src/components/FormFields/index.js, src/components/HelFormFields/HelLabeledCheckboxGroup.js, src/i18n/fi.json, src/validation/validationRules.js
Display in two columns in large screens (col-lg-6), and in one column in mid-size screens (col-md-12), to prevent label text from overlapping. 
Also, fix to a form validation bug caused by issue #162.
=> #161 Display all category lists in two columns

src/assets/main.scss, src/components/EventGrid/index.js, src/components/FilterableEventTable/index.js, src/components/FilterableEventTable/index.scss, src/components/FormFields/index.js, src/components/Header/index.scss, src/components/HelFormFields/HelDatePicker.js, src/components/HelFormFields/HelLanguageSelect.js, src/components/HelFormFields/NewEvent.scss, src/components/ImagePicker/index.scss, src/components/SearchBar/index.js, src/components/SearchBar/index.scss, src/components/ValidationPopover/index.scss, src/views/Editor/index.scss
- Fixed margins, paddings, button text visibility, etc. so that elements don’t overlap in mobile. 
- Fixed the tapahtumien hallinta -view on mobile, so that text doesn’t overlap. When designing the look of tables on mobile, there are basically only four options; to 1) squish columns together, 2) enable horizontal scrolling, 3) collapse rows under each other, or 4) collapse columns under each other. In this case it was decided to use option number 3, to collapse rows, so that information is easily visible on mobile. 
- Fixed date picker, so that it closes after user has made a new selection, instead of staying open.
- Moved the floating report error-icon a bit lower, but kept in on the left hand side, since once the error notice slider text is more intuitive if it slides out from the left …
=> #167 Optimize UI mobile usability

config/webpack/dev.js
This broke disabling raven through environment. Ie. raven_id was set to "false" instead of false
=> config: turn on nconf environment parsing to support booleans

src/utils/formDataMapping.js, src/views/App/index.js
This should fix the adding of subevents and also the confirmation dialog button text & color which were still using the Material-UI pre v1 syntax.
=> 268 lisaa uusi ajankohta does not work

src/actors/validator.js
Fixes #298.
Fixed route reading from state when clearing validation errors. The route location in state changed when we upgraded to react-router v4.
=> Fixed route reading from state when clearing validation errors.

src/components/FormFields/index.js, src/components/HelFormFields/HelOffersField.js, src/components/HelFormFields/NewOffer.js, src/validation/validator.js
Resolves #278. 
Changed the required fields in the Price information-section ("Hintatiedot") so that only Price ("Hinta") will be set as mandatory. Hinta-field marked with an asterisk to indicate compulsory nature. Set the Hinta-field as the topmost field in its section. Changed the instruction-text of price fields.
Also fixed "is free" field initialization on copied events which have a price.
=> change required price fields and fix isfree field on copied offers

src/components/HelFormFields/MultiLanguageField.js
Fixes #301.
Firefox does not have DOM event attached to global window (like Chrome & IE) so we pass the React synthetic event to parent component blur handler (if parent blur handler is defined).
=> Firefox event passing fix for event price

.travis.yml
Previously travis only installed dependencies. Building is the basic sanity check.
=> Really build the project in Travis

src/components/HelFormFields/HelAutoComplete.js, src/components/HelFormFields/HelDatePicker.js, src/components/HelFormFields/HelDateTimeField.js, src/components/HelFormFields/HelTextField.js, src/components/RecurringEvent/index.js, src/components/SearchBar/index.js
React-bootstrap FormControl component no longer have and respect `type` props, now changed to `componentClass`
https://react-bootstrap.github.io/components/forms/#forms-props-form-control
Fix for #341
=> [Fix] Fix multiline input field not having word-wrap break-word functionality 

src/validation/validator.js
Validation for event form disappeared due to a deprecated lodash function. Updated.
=> fix validation fails due to lodash deprecation

src/actions/editor.js, src/utils/helpers.js, src/views/Event/index.js, src/views/Search/__snapshots__/Search.test.js.snap
Fix for issue #311 and #279. Notices:
- Now before copy from an existing event to a new draft, the existing event data will be validated.
- After validating, all invalid fields will be emptied based on their types: `array -> []`, `object -> {}`, `string -> ''` ...etc
- Fields with tricky types (if there is any) like `null`, `undefined`, `boolean`... should be left unchanged.
There is no validation for `location` and `keywords` in UI. Maybe these should to a later separate issue.
=> validate and remove conflict data when copy event to new draft

src/components/HelFormFields/NewEvent.js
Fix #373 .
Turned out that, this [PR](https://github.com/City-of-Helsinki/linkedevents-ui/pull/361) for issue #312 only removes the default display of additional datetimes without changing the initial values of corresponding datetimes in the store. Since now the new datetime is generated with empty value by default, we can put the UI default display for datetime fields back again.
=> fix non-displayed addtional datetimes when use recurring tool

src/components/RecurringEvent/index.js
Resolved #372 
Note:
- the datetime user entered before generating recurring events with recurring tools will not be updated accordingly since it's unnecessarily complicated. Example below.
After using recurring tool:
=> fix empty end time field cause moment to use current time

src/views/Event/index.js
Using the delete button on event preview page doesn't delete also the related sub events. Fixed. 
=> Fix delete button on event preview page

__mocks__/testMocks.js, src/views/EventListing/EventListing.test.js, src/views/EventListing/__snapshots__/EventListing.test.js.snap
Notes:
- use mock date object instead of `window.Date` for test case require relative dates calculation
- mock date can use any date as current time. For test cases EventList component, current time is pinpointed to 11/2018
=> add mockdate to pinpoint fixed current time for relative dates testing

src/components/HelFormFields/NewEvent.js, src/components/HelFormFields/NewOffer.js
re-positioning delete button in events and offers form section:
- vertically align with top of the element
- got the right padding correctly (resolved overlap)
=> re-position buttons for elements in offers and events section

src/components/FilterableEventTable/EventRow.js
Resolved issue #417 . Now cancelled super events are also expandable/collapsible in Manage Events view
=> allow collapse/expand for cancelled super events in Manage Events view

src/components/RecurringEvent/index.js
- if user has some initial input for datetime in event form, the recurring tool should suggested initial starting time as 1 week from user's initial input
- if user has no initial input for datetime, the recurring tool should have empty suggestion for its datetime range
=> increment suggested starting datetime in recurring tool

src/utils/formDataMapping.js
Previously event preview required course fields to be present in
incoming data even when ui mode was something else than "courses".
=> Fix event preview bug with course fields

src/components/HelFormFields/NewOffer.js, src/validation/validator.js
Fixes #408 
- Offers are now validated separately from others to fix issues with conflicting field naming
- The offer description field is now validated using the longString rule. It wasn't validated / didn't work before.
=> Validate info url like other links

src/actions/editor.js, src/components/HelFormFields/HelLanguageSelect.js, src/utils/helpers.js, src/validation/validationRules.js
This PR fixes #435 
- Fix issue where the values of deselected languages weren’t nullified
- Multiple language fields for offers are now nullified, they weren’t before
- Validation is now run after the multiple language field values have been nullified. This fixes the issue where invalid values for deselected languages triggered validation warnings
- Unselecting all languages is no longer possible
=> #435 - Fix validation with multiple languages

src/components/EventGrid/index.js, src/views/Search/index.js
https://github.com/City-of-Helsinki/linkedevents-ui/issues/244
I also needed to change EventGrid so that it doesn't crash when event doesn't have fi, en, or sv values for name and subject fields. This is possible when events are searched without search text.
=> 244: Allow searching for events in a time range without search text

package.json, src/actions/events.js, src/api/client.js, src/components/EventDetails/index.js, src/constants.js, src/i18n/en.json, src/i18n/fi.json, src/index.js, src/store.js, src/utils/locale.js, src/views/Editor/index.scss, src/views/Event/index.js, src/views/Event/index.scss, yarn.lock
https://github.com/City-of-Helsinki/linkedevents-ui/issues/433
Add publisher information under event actions and under event location for event page.
Added also a rest API client for fetching the publisher's information. 
I also refactored and cleaned a bit the event page/event details code.
=> 433: Display event publisher in event preview

src/components/ImageEdit/index.js, src/components/ImageEdit/index.scss, src/i18n/en.json, src/i18n/fi.json
Add help notice text on image upload form. Add missing English and Finnish translations to image modal fields.
=> Add link to help page & add missing translations

src/actions/user.js, src/components/Header/index.js, src/utils/user.js, src/views/Editor/index.js, src/views/Event/index.js, src/views/Moderation/Moderation.js
Show moderation page / fetch moderation data based on organizations that have regular users rather than affiliated organizations
**NOTE:** The changes are done with the assumption that the user is an admin in the organizations, but that they don't need to be affiliated with the organization that the user belongs to.
=> Show Moderation page based on has_regular_user field

src/actions/userImages.js, src/components/HelFormFields/HelTextField.js, src/components/ImageEdit/index.js, src/components/ImagePicker/__snapshots__/ImagePicker.test.js.snap, src/components/ImagePicker/index.js
This pull request fixes issue https://github.com/City-of-Helsinki/linkedevents-ui/issues/537.
The event title disappeared because the image caption field's name attribute used the "name" value and was defined as a HelTextField element. The HelTextField element updates the store on the blur event and because the name of the caption field was "name", it collided with the event's title which is also stored in the store under the "name" key. Thus, the image caption field overrode the event title. Since the event title is an object and the image caption just a string, the event title appeared as an empty field in the UI.
The fix is to replace the HelTextField elements with ordinary TextField elements.
=> Fix event title field text disappearing when editing the image caption field

src/components/ImageThumbnail/index.js
Fix `ImageEdit` crashing by passing the required `onSave` prop.
=> Pass missing onSave prop to ImageEdit
