City-of-Helsinki/linkedevents-ui

src/editor.cjsx, src/search.cjsx, src/typeahead.cjsx
Relates to https://github.com/City-of-Helsinki/linkedevents/pull/57
=> Make POSTing new events work with the new changes to the API.

dev_server/getSettings.js, package.json, src/components/FilterableEventTable/index.js, src/views/EventListing/index.js
=> #24 and fix dev server

src/components/FormFields/index.js, src/components/HelFormFields/HelAutoComplete.js, src/components/HelFormFields/HelCheckbox.js, src/components/HelFormFields/HelDateTimeField.js, src/components/HelFormFields/HelLabeledCheckboxGroup.js, src/components/HelFormFields/HelOffersField.js, src/components/HelFormFields/HelSelect.js, src/views/Editor/index.js, src/views/EventListing/index.js
=> Fix IE10 editor bug #44

src/actions/userImages.js, src/components/ImageGalleryGrid/index.js, src/components/ImagePicker/index.js, src/reducers/images.js
giving feedback on image creation with flashmsg
=> new image appears at first position

src/assets/main.scss, src/components/FilterableEventTable/index.js, src/components/FilterableEventTable/index.scss, src/views/Event/index.js, src/views/Event/index.scss
=> added visual hints for draft events

src/actions/editor.js, src/actions/user.js, src/components/Header/index.js, src/components/Header/index.scss, src/constants.js, src/reducers/editor.js, src/reducers/user.js, src/utils/formDataMapping.js, src/validation/validationRules.js, src/validation/validator.js, src/views/Editor/index.js, src/views/Event/index.js, src/views/EventCreated/index.js
Event canceling, event fetching, editor buttons improved, organization fetching
=> Event canceling, event fetching, editor buttons improved, organization fetching

src/components/FormFields/index.js, src/components/HelFormFields/HelTextField.js, src/components/HelFormFields/MultiLanguageField.js, src/i18n/fi.json, src/validation/validationRules.js, src/validation/validator.js
Validation for short description. 
Also has multiline text editing fix and event-language getting fix (event description languages were not fetched properly from store so UI forgot which languages were selected when coming back to event editing).
=> Validation for short description. Also has multiline text editing and event-language fix

src/components/HelFormFields/HelOffersField.js
=> Take initial value of free checkbox into account

src/components/EventGrid/index.js
=> Fix event images in event grid

src/components/FormFields/index.js, src/validation/validationRules.js, src/validation/validator.js
=> Do not ignore invalid URLs when submitting event form

src/components/HelFormFields/HelDateTimeField.js
If the value is invalid set null state to the store, but don't nullify
the field.
Closes #132
=> Fix datetime validation

package.json
In addition to consistency, building is arguably what is happening here
=> Rename deploy to build for consistency between projects

src/actions/userImages.js, src/components/ImagePicker/index.js, src/i18n/fi.json
Added delete button to image picker.
<br>
=> Image delete

config/webpack/dev.js, config/webpack/prod.js, package.json, src/actors/serializer.js, src/assets/main.scss, src/index.jade, src/index.js
Renders commit hash to app's index.html
=> Feature commit hash render

config/webpack/dev.js, config/webpack/prod.js, package.json, src/assets/main.scss, src/index.jade
Showing testing banner with link to production instance (as given in configuration)
=> Feature testing message

src/components/HelFormFields/HelOffersField.js, src/validation/validationRules.js, src/validation/validator.js
Remove Price information as a required field
=> Remove Price information as required field #163

src/components/FormFields/index.js, src/components/HelFormFields/HelTextField.js, src/i18n/fi.json, src/validation/validationRules.js, src/validation/validator.js
Add character counter to description field (Kuvaus)
=> #162 - Add character counter to description field (Kuvaus)

src/components/EventGrid/index.js, src/components/EventGrid/index.scss
Display event start date in search results
=> #166 - Display event start date in search results

src/components/HelFormFields/HelCheckbox.scss
Fixes as request; to display long words in tablet width properly.
=> #161 Fixes to UI in tablet width

src/components/SearchBar/index.js
Autofocus on input field, change text, and remove default time display, as requested.
=> #164 Autofocus on input field

src/components/FilterableEventTable/index.scss, src/components/ImageEdit/index.scss, src/components/ImageThumbnail/index.js, src/components/ImageThumbnail/index.scss
Display edit icon on the right hand side, change the width of the save button in 'edit image' info view,  add margin-top between the image and save button in the same view.
=> #165 Display edit icon on the right hand side

src/components/FormFields/index.js, src/components/HelFormFields/HelDatePicker.scss, src/components/ImagePicker/index.scss, src/components/RecurringEvent/RecurringEvent.scss
Fix modal width, change width of the recurring event modal, and add line between event times, as requested.
=> #167 Fixes to mobile UI

src/components/FormFields/index.js, src/components/HelFormFields/HelDatePicker.scss, src/components/HelFormFields/NewEvent.js
Fixed line between new events, in editing mode.
=> #167 fix line between events

src/components/EventDetails/index.js, src/components/FormFields/index.js, src/i18n/fi.json
=> Add input field and value for event organizer

src/reducers/editor.js
=> Persistent info tags when editing event

src/components/EventDetails/index.js, src/components/EventDetails/index.scss
=> Resize image to viewport size

src/components/HelFormFields/HelDateTimeField.js, src/validation/validationRules.js
Fixes #238 . Regexp on validationRules changed to allow 24:00 and also changed HelDateTimeField to handle 24:00 correctly.
=> Changed time validation to allow entering 24:00 as time.

src/reducers/editor.js
Fixes #272. Added missing if statement from editor reducer.
=> Added missing "else" statement from editor reducer

src/validation/validationRules.js
Fixes #275. Fixed event saving when user has not clicked info_url (kotisivu) field before save.
=> Fixed event saving when kotisivu not clicked before save

src/components/ImageEdit/index.js, src/components/ImagePicker/index.js, src/views/App/index.js
Fixes #293. Added missing button captions & fixed styling on image picker/edit components.
=> Added missing button captions & fixed styling on image picker/edit

src/i18n/fi.json, src/views/EventCreated/index.js
Resolves #35.
Implements moving to event preview page after publish/save.
=> Implemented moving to event preview page after publish/save.

src/components/Header/index.js, src/components/Header/index.scss
Fix #288
Second issue seems like have been fixed already
=> [Feature] Add spacing between svg and translated text on navbar

src/assets/main.scss, src/components/FormFields/index.js, src/components/HelFormFields/HelCheckbox.scss, src/components/HelFormFields/HelLanguageSelect.js, src/components/HelFormFields/HelOffersField.js, src/components/HelFormFields/HelOffersField.scss, src/views/Editor/index.scss
=> [Fix] Make language selection checkboxes align neatly 

src/assets/_button.scss, src/assets/main.scss, src/components/FormFields/index.js, src/components/HelFormFields/HelAutoComplete.js, src/components/HelFormFields/HelDateTimeField.js, src/components/HelFormFields/HelLabeledCheckboxGroup.js, src/components/HelFormFields/HelOffersField.js, src/components/HelFormFields/HelOffersField.scss, src/components/HelFormFields/HelTextField.js, src/components/HelFormFields/MultiLanguageField.js, src/components/HelFormFields/NewOffer.js, src/components/RecurringEvent/RecurringDateRangePicker.js, src/components/RecurringEvent/RecurringEvent.scss, src/components/RecurringEvent/index.js, src/i18n/en.json, src/i18n/fi.json, src/views/Editor/index.js, src/views/Editor/index.scss, src/views/Event/index.js, src/views/Event/index.scss
=> [Fix] Fix some props type warning, style issue of recurring events, cleanup some inline styling

src/components/HelFormFields/NewEvent.js
This PR fixes the date prefilling in new event creation for issue #312
=> Fix remove date prefilling in new event creation

src/components/EventDetails/index.js, src/utils/checkEventEditability.js, src/views/Event/index.js, src/views/EventCreated/index.js
Fix for issue #314  Add cancel and delete buttons to event preview
=> Add cancel and delete button to preview

src/components/HelFormFields/HelDatePicker.js, src/components/RecurringEvent/index.js, src/views/Search/__snapshots__/Search.test.js.snap
When choose a date from the datepicker in SearchBar, the changed value is not shown. This is a fix for that.
=> fix datepicker not show value

src/components/FormFields/index.js, src/validation/validator.js
changes in validation for displaying sub_events errors causes trouble with validating the form when submitting.
=> fix sub_events validation stop the form submission

src/views/Event/index.js
- made a mistake with that previous PR for issue with delete button. Fix pushed
=> update delete function

src/views/Event/index.js, src/views/Event/index.scss
This PR fixes minor design stuff suggested by Aleksi in this issue
https://github.com/City-of-Helsinki/linkedevents-ui/pull/362
=> Minor fix design stuff

src/views/EventCreated/index.js
This PR resolves #383 
The message box disappears after 5 seconds.
=> Make saved successfully message box impermanent

src/actions/editor.js, src/components/FormFields/index.js, src/views/Editor/index.js
- remove adding sub events in editing form
- fix buttons text for form actions
- fix non-resolved loading sign when try to submit/save form
=> remove adding sub events for editing form, fix UI and state issues

src/components/FilterableEventTable/EventRow.js, src/components/FormFields/index.js, src/utils/formDataMapping.js
treat all non-super events the same, datetime field is editable
=> make datetime editable for non-super events

src/components/HelFormFields/HelTextField.scss
=> fix border in focused state with text input

src/components/HelFormFields/HelTextField.scss
This should fix the red border problem
=> Fix for removing border from the text input field

src/components/ImagePicker/index.scss
- revert the UI for image dialog to resemble the version before big UI updates
=> fix image dialog crippled UI

src/actions/userEvents.js
PR for the issue #358 
Note : User editable events should display as expected after backend implementation
=> 358 display all user editable events in manage event panel

src/actions/editor.js
=> remove superevent status when copy a draft from an existing event

src/actions/organization.js
cant exactly reproduce the case where dissolved organization causes an issue due to my test account. Probably you gotta check it yourself
=> excluded dissolved instance from organizations list

src/components/Header/index.js
=> hide create-event button when inside creating event form

src/actions/editor.js
Resolve #419 
- after done editing sub-event/non-super event, re-fetch subevents data to update Manage Events page
- also refactor redux thunk inside `src/actions/editor.js` for chaining dispatch
=> re-fetch sub events after editing

src/utils/raven_reporter.js
Get user and debug message separate from redux state for easier reporting.
=> Raven reporter structural fixing

src/views/Help/index.js
Courses related content updated.
=> Courses related content update for index.js

src/i18n/fi.json
Fix #441 
Changed text in image-caption-limit to suggested text.
=> Change image tool label

src/validation/validationRules.js
=> Disallow empty strings (WIP)

src/actions/editor.js
Fixes #456
Get content languages from copied event data instead of the state
=> Fix copy to draft bug

src/components/EventDetails/index.js, src/components/EventDetails/index.scss, src/components/LinksToEvents/LinksToEvents.js, src/components/LinksToEvents/LinksToEvents.scss, src/i18n/en.json, src/i18n/fi.json
Fixes: #381 
- Create component for event links
- Display links to event sub events
- Display badges for sub events
=> #381 - Display sub-events in a super-event's preview

src/components/FormFields/index.js, src/components/RecurringEvent/index.js
Fill initial values based on form start & end dates
=> Fix recurring event modal default values

src/actions/editor.js
=> #412 - Append text about service centre card pertinently

src/views/App/index.js, src/views/Help/index.js
Update LE UI contact information
[LINK-65](https://helsinkisolutionoffice.atlassian.net/browse/LINK-65)
=> LINK-65 | Update contact information
